# main site metadata and titles
site_name: rcpch.tech
site_description: RCPCH Incubator Landing pages
site_author: The Royal College of Paediatrics and Child Health
site_url: https://rcpch.tech

# copyright information which is shown in the footer
copyright: Copyright &copy; 2024 Royal College of Paediatrics and Child Health (RCPCH)

# these lines configure the 'GitHub repo' widget on the top right
# COMMENTED OUT AS NOT REALLY NEEDED FOR POC rcpch.tech SITE 20.03.2024
# repo_url: https://github.com/rcpch/rcpch.tech
# repo_name: rcpch/rcpch.tech
# edit_uri: blob/live/docs

# `mkdocs serve` serves the documentation at custom port (to avoid clashing with other services we commonly run)
dev_addr: "0.0.0.0:8000"

# theme settings, fonts, colours
theme:
  name: material
  #custom_dir: rcpch-theme
  features:
    # - content.action.edit # COMMENTED OUT AS NOT REALLY NEEDED FOR POC rcpch.tech SITE 20.03.2024
    # - content.action.view # COMMENTED OUT AS NOT REALLY NEEDED FOR POC rcpch.tech SITE 20.03.2024
    - navigation.expand
    - navigation.footer # explicitly adds footer prev/next (Material4MkDocs9.0)
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # - toc.integrate

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode


  font:
    text: Montserrat
    code: Roboto Mono

  favicon: _assets/_images/dynamic-child-favicon.png
  logo: '_assets/_images/rcpch_logo.png'

# mkdocs plugins
plugins:
  # COMMENTED OUT AS NOT REALLY NEEDED FOR POC rcpch.tech SITE 20.03.2024
  # - git-committers:
  #     repository: rcpch/rcpch.tech
  #     branch: live
  #     enabled: !ENV [ENABLE_GIT_COMMITTERS, false] # makes Git Committers optional
  # - git-revision-date-localized:
  #     enable_creation_date: true
  - search
  # COMMENTED OUT AS NOT REALLY NEEDED FOR POC rcpch.tech SITE 20.03.2024
  # - with-pdf:
  #     back_cover: false
  #     cover_title: rcpch.tech
  #     cover_subtitle:
  #     exclude_pages:
  #       - 'home/download/'
  #     output_path: pdf/rcpch-tech.pdf
  #     enabled_if_env: ENABLE_PDF_EXPORT
  #     #debug_html: true
  #     #show_anchors: true
  #     #verbose: true

# additional markdown features
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

# set extra CSS file
extra_css:
  - _assets/_stylesheets/extra.css

# footer links and variables
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rcpchtweets
    - icon: fontawesome/brands/github
      link: https://github.com/rcpch
